- src/config.ts
- src/diff.ts
- src/types/config.d.ts
- test/cmd/pipeline.test.ts
- test/projects/simple/.buildkite/pipeline.changed.yml
> feat(core): always treat pipeline changes as matching that pipeline

- CHANGELOG.md
- README.md
- bin/monofo.js
- docker-compose.yml
- src/config.ts
- src/pipeline.ts
- src/types/config.d.ts
- test/cmd/pipeline.test.ts
- test/config.test.ts
- test/diff.test.ts
- test/projects/simple/.buildkite/pipeline.dependedon.yml
- test/projects/simple/.buildkite/pipeline.foo.yml
Adds support for the `monorepo.depends_on` configuration option
> feat(core): Add support for depends_on at a pipeline level

- package.json
- src/cmd/pipeline.ts
- test/cmd/exec.ts
- tsconfig.json
- yarn.lock
Uses @tsconfig/node12 to clean up the tsconfig
> Clean up tsconfig

- src/config.ts
- src/hash.ts
- test/cmd/pipeline.test.ts
- test/projects/pure/foo/pipeline.yml
`nodir` option is the answer
Additional output is for use with next PR
> fix: error when we attempt to checksum a directory

- src/decide.ts
- test/cmd/pipeline.test.ts
Currently, pure cache hits cause PIPELINE_RUN_ALL to be ignored for those configs.
> PIPELINE_RUN_ALL should override pure cache hits

- src/decide.ts
- test/cmd/pipeline.test.ts
As requested in that earlier PR
> feat: allow mixing PIPELINE_RUN_ALL and PIPELINE_NO_RUN_TASK

- src/config.ts
- src/decide.ts
- src/merge.ts
- test/cmd/pipeline.test.ts
Set an environment variable containing the base build used for artifacts etc.
Fixes #158
> feat(core): set MONOFO_BASE_BUILD_ID env var

- src/config.ts
- test/config.test.ts
- test/projects/invalid/pipeline.invalid.yml
> feat(config): print warning log when invalid attributes are found on `monorepo` block

- package.json
- yarn.lock
I suspect these two packages need to be updated together to get either change to pass
> Combined update branch

- src/config.ts
- test/cmd/pipeline.test.ts
- test/config.test.ts
- test/diff.test.ts
- test/projects/kitchen-sink/.buildkite/pipeline.match-all-boolean.yml
- test/projects/kitchen-sink/.buildkite/pipeline.match-all-false.yml
- test/projects/kitchen-sink/.buildkite/pipeline.match-all-true.yml
> If a config matchesAll, it doesn't matter if there are no changes

- docs/diff.md
- src/buildkite/client.ts
- src/buildkite/config.ts
- src/cmd/base-commit.ts
- src/cmd/hash.ts
- src/cmd/install.ts
- src/cmd/list.ts
- src/cmd/pipeline.ts
- src/cmd/record-success.ts
- src/cmd/uninstall.ts
- src/diff.ts
- src/git.ts
- src/handler.ts
- src/types/buildkite.d.ts
- src/util.ts
- test/buildkite/client.test.ts
- test/cmd/base-commit.test.ts
- test/cmd/hash.test.ts
- test/cmd/list.test.ts
- test/cmd/pipeline.test.ts
- test/diff.test.ts
Fixes #224 - see especially the revised thinking at https://github.com/vital-software/monofo/issues/224#issuecomment-865391348
Direction of changes documented in repo at https://github.com/vital-software/monofo/blob/feature/integration-branch-support/docs/diff.md
> Support MONOFO_INTEGRATION_BRANCH as distinct from default branches

- src/buildkite/client.ts
- src/diff.ts
- test/buildkite/client.test.ts
> fix(client): fix url parameter mistakes that lead to filtering by branch not working

- src/diff.ts
It's a git convention that the first parent of a merge commit is what was already on the branch being merged into. In other words, when using `git rev-list --first-parent main`, we're usually viewing a list of commits that happened on main
However, this is just a _convention_ followed by the porcelain git commands, like `git merge`; it's not a universal rule written into every git client. Some git clients seem to create merges with main as the second parent, and there might be cases where it makes sense that the merge was in the opposite direction from usual.
At the same time, the reason we use `--first-parent` is to attempt to support branches of arbitrary length, so it'd be good not to lose that.
Combine (with union) the set of commits from `--first-parent` and the set of commits …
> fix(diff): look through more commits to find a base build, including second parents

- src/diff.ts
> fix(diff): reverse order of logic to allow integration builds

- docs/diff.md
- src/diff.ts
Gives a few extra debug messages from the diff module, and fixes a spelling mistake in documentation
> chore(log): Log the type of diff operation being considered

- .buildkite/pipeline.test.yml
- .eslintrc.js
- src/cmd/base-commit.ts
- src/cmd/hash.ts
- src/cmd/install.ts
- src/cmd/list.ts
- src/cmd/pipeline.ts
- src/cmd/record-success.ts
- src/cmd/uninstall.ts
- src/config.ts
- src/handler.ts
- src/hash.ts
- src/types/cmd.d.ts
- src/util.ts
- test/cmd/exec.ts
- test/steps/record-success.ts
- tsconfig.eslint.json
- Enables missing airbnb base rules
- Disables some rules that were at warning level
- Fixes any lint violations
- Adds a CI step to check the lint
> style(eslint): enable missing base airbnb rules

- src/config.ts
- test/artifacts/compression.test.ts
- test/commands/download.test.ts
- test/commands/pipeline.test.ts
- test/config.test.ts
- test/diff.test.ts
- test/projects/kitchen-sink/.buildkite/pipeline.match-all-env.yml
- test/reason.test.ts
> fix: allow pipelines with empty `steps`

- .buildkite/pipeline.env.yml
- .run/monofo deflate node-modules.tar node-modules.caidx.run.xml
- .run/monofo deflate node-modules.tar node-modules.tar.lz4.run.xml
- src/artifacts/compression/compression.ts
- src/artifacts/compression/desync.ts
- src/artifacts/compression/gzip.ts
- src/artifacts/compression/index.ts
- src/artifacts/compression/lz4.ts
- src/commands/deflate.ts
- src/commands/upload.ts
- test/artifacts/compression.test.ts
Need to write two files: a credentials file and a config file
> fix: instance profile credentials config file

- src/artifacts/matcher.ts
- src/util/tar.ts
- test/util/tar.test.ts
And feat: depth-sort on file arguments to tar
Fixes #338
> feat: show tar version in use

- docs/artifacts.md
- src/artifacts/api.ts
- src/artifacts/compression/compression.ts
- src/artifacts/compression/desync.ts
- src/artifacts/compression/gzip.ts
- src/artifacts/compression/index.ts
- src/artifacts/compression/lz4.ts
- src/artifacts/compression/tar.ts
- src/artifacts/matcher.ts
- src/commands/deflate.ts
- src/commands/upload.ts
- src/util/exec.ts
- src/util/helper.ts
- src/util/tar.ts
- test/artifacts/compression.test.ts
- test/artifacts/matcher.test.ts
- test/commands/upload.test.ts
- test/util/helper.test.ts
> fix: use recursive file lists (--files-from within --files-from) to allow GNU tar to produce better artifacts

- package.json
- src/artifacts/compression/desync.ts
- test/commands/upload.test.ts
Probably because something went wrong when retrieving credentials, and we silently gave up
> fix: EOF while trying to read config file

- src/artifacts/api.ts
- src/util/got.ts
Specifically, this should effectively increase the connect timeout, which might be important here
Hopefully helps with #372
> fix: configure got timeouts in detail
