vital-software/monofo-buildkite-plugin

src/config.ts
test/cmd/pipeline.test.ts
test/config.test.ts
test/projects/simple/.buildkite/pipeline.unreferenced.yml

toposort only returns nodes that are mentioned in the edges - toposort.array is what we want; it always returns the same number of nodes as it was given.

fix(config): include components that have no incoming edges

---

.buildkite/pipeline.yml
src/pipeline.ts
test/cmd/pipeline.test.ts
test/projects/crossdeps/.buildkite/pipeline.baz.yml
test/projects/crossdeps/.buildkite/pipeline.foo.yml

If we aren't replacing any actual artifacts in the build, we don't need to add an artifact step. And if we don't, we should replace _skipped depends_on keys_ with _nothing_ rather than _the replacement artifact-step key_ (current behavior).
Fixes a bug where we would leave the build hanging, waiting for an artifact step that was never added.

Don't depend on artifact step if it's not needed

---

src/steps.ts
test/cmd/pipeline.test.ts
test/projects/crossdeps/.buildkite/pipeline.baz.yml
test/projects/crossdeps/.buildkite/pipeline.foo.yml

Exclude artifacts starting with `.phony/` from the actual upload/download attempt made as part of monofo. They remain part of sorting the subpipelines. This means we can now arbitrarily order pipelines.
A better way would have been to add `before`/`after` properties to the config, but this is such a slim one-line change it's hard to resist. I can see why `make` follows this pattern.

feat(steps): allow for phony dependencies

---

src/config.ts
src/pipeline.ts
src/types/config.d.ts
test/cmd/pipeline.test.ts
test/projects/simple/.buildkite/pipeline.bar.yml

This allows e.g. setting NODE_IMAGE="node-${BUILDKITE_BUILD_NUMBER}" if a certain pipeline is included, and NODE_IMAGE="node-1.0.0" if it's not

feat(core): allow setting env values when excluded

---

.buildkite/pipeline.yml

NPM_TOKEN was removed from the default secrets, so we have to include it explicitly.
Should fix the broken master builds.

build: add NPM_TOKEN secret from Secrets Manager

---

src/cmd/pipeline.ts
src/decide.ts
src/merge.ts

Just a straight refactor, splitting pipeline.ts into two parts, 'decide' and 'merge'.

refactor(core): split pipeline logic into decide and merge

---

src/decide.ts

> If pattern is a string, only the first occurrence will be replaced.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

Replace all dashes

---

README.md
src/cmd/pipeline.test.ts
src/config.test.ts
src/config.ts
src/decide.ts
src/diff.test.ts
src/merge.ts
test/fixtures.ts
test/projects/kitchen-sink/.buildkite/pipeline.some-long-name.yml

- Adds support for PIPELINE_RUN_ONLY=component-name
- Adds a test for PIPELINE_NO_RUN=*
- Adds a regression test for multiple dashes in the component name
Longer term but not done here, we should probably move to `PIPELINE_RUN='foo bar baz'` or something, so that all the env vars work the same (component name in value not key)

feat: PIPELINE_RUN_ONLY=component-name

---

src/steps/artifact-injection.ts
src/types/buildkite.d.ts
test/cmd/pipeline.test.ts

Downloads and uploads across files will now happen in parallel. And for each file, the upload will start as soon as the download is ready.
The produced command step is a bit uglier, because we're not using the artifacts plugin. But developers don't really see that anyway.

feat: copy artifacts in parallel

---

package.json
src/config.ts
src/hash.ts
yarn.lock

I first tried to optimize the I/O of the hashing, but profiling revealed most of the time was spent in the glob. `glob` accepts a number of options where you can pass a shared object to cache stat information between calls.

perf: cache stat calls made by glob, limit concurrency when hashing files

---

src/config.ts
src/decide.ts
src/diff.ts
test/cmd/pipeline.test.ts
test/config.test.ts
test/diff.test.ts
test/projects/kitchen-sink/.buildkite/pipeline.match-all-boolean.yml
test/projects/kitchen-sink/.buildkite/pipeline.match-all-mixed.yml
test/projects/kitchen-sink/.buildkite/pipeline.match-all.yml

This is a small display improvement which stops the output from listing all the files in the repo multiple times when there are pipelines that match everything.
It also adds support for `matches: true`

feat: track when a pipeline has matched everything, and don't list all the files

---

src/cmd/hash.ts
src/cmd/list.ts
src/config.ts
test/cmd/hash.test.ts
test/cmd/list.test.ts

Adds two new commands, `list` and `hash`. These use the globbing and matching logic, but allow other tools to do things with the list of files, or the content hash

feat: add commands to list and hash components

---

.buildkite/pipeline.yml
docker-compose.yml

Moved away from Quay
Fixes build failures seen in renovate branches. Was missed from original migration because I was only looking for private repos.

build(docker): change build-cache repository to ECR

---

src/config.ts
src/decide.ts

When providing `matches: false` with an explicit boolean, take this to mean that we shouldn't then automatically add the pipeline.yml file to the list of matches. That'll prevent it running when modified.
Also excludes such pipelines from `PIPELINE_RUN_ALL`
Fixes #195
Fixes #198

feat(config): make matches: false ignore self-changes to its pipeline

---

src/buildkite/config.ts

This environment variable takes precedence over BUILDKITE_PIPELINE_DEFAULT_BRANCH, allowing a different default branch to be temporarily assumed.
fixes #201

Allow overriding the default branch via MONOFO_DEFAULT_BRANCH

---

src/decide.ts

If `matches === false`, the fallback should be for this component to be excluded, because it usually
represents a task that can only otherwise be run with `PIPELINE_RUN_` env vars.
Put another way, this means that monofo won't make all the _task_ pipelines run when there's no base build found (due to an error or a fresh pipeline etc.)

fix(config): fallback for never-matched tasks should be excluded, not included

---

.gitignore
src/cmd/list.ts
src/config.ts
src/decide.ts
src/diff.ts
test/diff.test.ts

Removes the `MatchResult` interface, because we don't actually have anything reading `matchesAll`/`matchesNone` anymore; anything that was reading it can instead access `config.monorepo.matches` (the raw `boolean | string[]`).

refactor(config): simplify the matching interface

---

src/branch-list.ts
src/config.ts
src/decide.ts
test/branch-list.test.ts
test/projects/branch-exclusion/.buildkite/pipeline.explicit-all.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-exclude-multiple.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-include-exclude-wildcard.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-include-exclude.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-include-multiple.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-none.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-one.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-wildcard-end.yml
test/projects/branch-exclusion/.buildkite/pipeline.explicit-wildcards.yml
test/projects/branch-exclusion/.buildkite/pipeline.implicit-all.yml
test/projects/branch-exclusion/.buildkite/pipeline.implicit-rest.yml

We would like the Buildkite branch filtering patterns (https://buildkite.com/docs/pipelines/branch-configuration#pipeline-level-branch-filtering), but set on a pipeline level so that we can still make use of (potential) artifacts produced by said pipelines. This requires the logic to go through monofo

[KATOA-3413] Add logic for branch inclusion/exclusion and tests

---

src/diff.ts
src/git.ts
test/diff.test.ts

We were using `git rev-parse` to check for existing commits (so that we don't use a commit that no longer exists in the repository as a base build). However, this doesn't validate a SHA-1 hash corresponds to a valid commit: it just accepts *any* valid SHA-1 hash and returns success. Whoops.
Instead, we should use `git cat-file -e HASH^{commit}` - this ensures that "HASH" can be treated as a commit (because it exists in the object DB)

fix(diff): fix integration strategy to check for existing commits with cat-file

---

src/diff.ts
src/git.ts

First job: knock out this stderr reporting, which is expected and is just noise
Second job: provide logging during `getMostRecentBranchBuild` so that it's clearer how the integration branch strategy is working

chore(diff): make process of finding integration diff quieter

---

src/buildkite/config.ts
src/config-file.ts
test/config.test.ts

In preparation for self-hosting (#271), we need to be able to exclude directories of pipeline files per monofo-installation. Specifically, we're interested in excluding our own `test/**/pipeline.*.yml` files that are used as test fixtures.

feat(config-file): Allow customizing PIPELINE_FILE_GLOB and PIPELINE_FILE_IGNORE_GLOB

---

src/steps/record-success.ts
test/cmd/pipeline.test.ts

This is dealing with the syntactic sugar that Buildkite adds around command/commands, and making sure we include both in the key of the step hash we're building

fix(pure): JSON stringify the commands so that if they're an array we still get them all

---

.buildkite/pipeline.release.yml
.buildkite/pipeline.test.yml
.buildkite/pipeline.typescript.yml
.npmignore
.nvmrc
README.md
docker-compose.yml
hooks/pre-command
hooks/pre-command.bats
package.json
plugin.yml
tsconfig.json
yarn.lock

Adds the ability to use monofo as a buildkite plugin.
Shortly after merging, we'll rename the repo to `monofo-buildkite-plugin` - this `-buildkite-plugin` suffix is required by Buildkite in order to use the repo as a plugin like:
```yaml
plugins:
[...]
- vital-software/monofo#v3.0.0:
generate: pipeline
```
Note that the CLI application, environment variables, NPM package, etc. will be unchanged - they'll still all just be `monofo` - renaming the repo just allows us to have a more straightforward usage path.
The only alternatives I could see would be:
- Sync the repo to another repository URL (annoying to have duplicates, etc.)
- Specify `ssh://git@github.com/vital-software/monofo.git#v1.0.0` every time we want to use the plugin (but this is annoying, presupposes git usage, is hard to …

feat: Add a standard way to load monofo via Buildkite plugin configuration

---

.buildkite/pipeline.node-modules.yml
.buildkite/pipeline.release.yml
.buildkite/pipeline.test.yml
.buildkite/pipeline.typescript.yml
plugin.yml

Uses the artifact support to drive the Monofo build using itself as a plugin (version 3.2.0 is hard-coded and won't be automatically updated, to prevent a bad release from breaking the build)

ci: add self-hosting configuration using 3.2 for artifacts

---

package.json
src/artifacts/compression/desync.ts
test/commands/upload.test.ts

Because otherwise time-limited credentials aren't supported
Because https://github.com/folbricht/desync/blob/651a6cea14a080326bb64b28b82c14495c2028ff/cmd/desync/config.go#L67

fix: add support for STS credentials via config file

---

.buildkite/pipeline.env.yml
.buildkite/pipeline.node-modules.yml
.buildkite/pipeline.release.yml
.buildkite/pipeline.test.yml
.buildkite/pipeline.typescript.yml
src/artifacts/compression/desync.ts

Swaps the file extension of the build artifacts to `.caidx`, telling Monofo to use `desync` to transparently deflate/inflate the archive

ci: use desync for build artifacts

---

src/decide.ts
src/reason.ts
test/commands/pipeline.test.ts
test/reason.test.ts

This makes `matches: true` useful for cases such as setting environment variables, or steps that must always be included.
Currently, they won't happen on e.g. task builds that use `PIPELINE_RUN_ONLY`; this change makes the exception for `matches: true` symmetrical with the exception for `matches: false` that causes opt-out of `PIPELINE_RUN_ALL`

feat: allow `matches: true` to opt out of PIPELINE_RUN_ONLY

---

.buildkite/pipeline.env.yml
.buildkite/pipeline.node-modules.yml
.buildkite/pipeline.plugin-lint.yml
.buildkite/pipeline.plugin-test.yml
.buildkite/pipeline.release.yml
.buildkite/pipeline.test.yml
.buildkite/pipeline.typescript.yml

And consolidate build envs
This is a "pre-cache pattern" that we've already used elsewhere, but we haven't tried it out using the new tooling yet.

ci: pre-cache node-modules.caidx into place

---

hooks/lib/generate.bash
src/artifacts/compression/gzip.ts
src/config.ts
src/decide.ts
src/reason.ts
test/reason.test.ts

In this build: https://buildkite.com/vital/monofo/builds/3246#2edc895a-b0dc-4f7f-bda3-a7b56f3e9b19
The `pipeline.env.yml` had `matches: true`, but it wasn't included!

fix: log the generated monofo command

---

.buildkite/pipeline.env.yml
.eslintrc.js
.gitignore
package.json
src/artifacts/compression/compression.ts
src/artifacts/compression/desync.ts
src/artifacts/compression/gzip.ts
src/artifacts/compression/index.ts
src/artifacts/compression/lz4.ts
src/artifacts/compression/tar.ts
src/commands/deflate.ts
src/commands/upload.ts
src/manifest.ts
src/util/tar.ts
test/artifacts/compression.test.ts
test/commands/upload.test.ts
test/manifest.test.ts
yarn.lock

- We were dropping the last block from the file list (tar argv input) - so a bunch of files were being skipped
- Globs were sent to tar as non-recursive, which is correct for some sorts of glob (ones that might match directories _and_ files), but incorrect for others (like a glob such as `./node_modules/` which should be passed on to tar as-is, in recursive-mode)

2 critical fixes

---

hooks/post-command
hooks/pre-command

We use the bash option `set -u` (or "nounset"), which errors if an unset bash variable is accessed, which we did in these `if` checks (so they'd never end up handling the error they intended to; they'd fail before running the `then`)
Now we will print a nice error message and exit politely

fix(hooks): make plugin conf checks safe for nounset

---

src/artifacts/model.ts
src/util/helper.ts
test/artifacts/model.test.ts
test/fixtures.ts
test/reason.test.ts

Relates to #358
Specifically, makes the workaround mentioned in that comment (setting an invalid build ID) cause an early exit, rather than erroring when the Buildkite API gives a 404 response
Has a matching test

fix(artifact): error early on non-uuid build ID

---

src/commands/pipeline.ts

Previously, `pipeline` was the default command, and would be called if you passed no sub-command. It's now just a normal command called 'pipeline'
BREAKING CHANGE: If you called `npx monofo` before, you'll now need to call `npx monofo pipeline` explicitly

feat(pipeline): removed the default command alias for pipeline

---

.buildkite/pipeline.node-modules.yml
.buildkite/pipeline.release.yml
.buildkite/pipeline.test.yml
.buildkite/pipeline.typescript.yml
src/util/helper.ts

`main` is currently blocked due to buildkite suddenly generating uuids that are version _seven_. This is breaking our `isUuid` regex, and breaking all builds.
Wikipedia article on uuid format: https://en.wikipedia.org/wiki/Universally_unique_identifier#Format
```
123e4567-e89b-12d3-a456-426614174000
xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx
The four-bit M and the 1 to 3 bit N fields code the format of the UUID itself.
The four bits of digit M are the UUID version, and the 1 to 3 most significant bits of digit N code the UUID variant. (See [below.](https://en.wikipedia.org/wiki/Universally_unique_identifier#Variants)) In the example, M is 1
```
Sample Id generated by a broken build: 
```
0180bb9f-c455-7877-b8b5-5a660404d36a
^ version character
```

Allow for uuids up to version 7
